global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'url_shortener_api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics' 
    #metrics_path: '/metrics': Prometheus will fetch metrics from the endpoint /metrics (e.g., http://api:5000/metrics).

